#!/bin/bash
set -e

BDIR=`cd $( dirname "${BASH_SOURCE[0]}" ) && cd .. && pwd`
cd ${BDIR}

function compile() {
    pkg -t linux index.js -o ./hack/build/web3
    docker build  -t web3:1.0 -f ./hack/web3.Dockerfile .
}

function start() {
    HTTP_PORT=5000 node index.js
}

function show_help(){
    cat <<-EOF
${@}
USAGE: ./hack/run [COMMANDS]

COMMANDS:
    compile
EOF
    exit 1
}

case "${1}" in
    compile)
        compile
        ;;
    start)
        start
        ;;
    -h)
        show_help
        ;;
    *)
        show_help "no command ${1}"
        exit 1
        ;;
esac
